name: Deploy to WP Engine Staging
on:
  push:
    branches:
     - staging
jobs:
  build:
    runs-on: ubuntu-latest  
    steps: 
    - uses: actions/checkout@v2
    - name: Deploy to WP Engine Staging
      uses: wpengine/github-action-wpe-site-deploy@v3.0
      with:
      # Deploy vars 
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
        WPE_ENV: responsibl1stg
        # Deploy Options
        REMOTE_PATH: "wp-content/plugins/site-functionality/"
        PHP_LINT: TRUE
        FLAGS: -azvr --inplace --delete --exclude=".*" --exclude-from=.gitignore
        CACHE_CLEAR: TRUE